markdown: kramdown
url: <%= url %>
baseurl:
exclude:
  - 'README.md'
  - '.gitignore'
  - 'package.json'
  - 'node_modules'
  - 'Gemfile.lock'
  - 'Gemfile'
  - 'composer.json'
  - 'svg-sprite.json'
  - 'webpack.config.js'
permalink: pretty
gems:
  - jekyll-sitemap
keep_files: ['assets']
title: <%= metatitle %>
description: <%= metadesc %>
